apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hasir.fullname" . }}-config
  labels:
    {{- include "hasir.labels" . | nindent 4 }}
data:
  HASIR_SERVER_PUBLICURL: "https://{{ .Values.global.domain }}/api"
  HASIR_SERVER_SSHHOST: "git@{{ .Values.global.domain }}"
  HASIR_SERVER_IP: "0.0.0.0"
  HASIR_SERVER_PORT: "8080"
  HASIR_POSTGRESQL_HOST: {{ include "hasir.postgresql.fullname" . | quote }}
  HASIR_POSTGRESQL_PORT: "5432"
  HASIR_POSTGRESQL_USERNAME: {{ .Values.postgresql.auth.username | quote }}
  HASIR_POSTGRESQL_DATABASE: {{ .Values.postgresql.auth.database | quote }}
  HASIR_SMTP_HOST: {{ .Values.config.smtp.host | quote }}
  HASIR_SMTP_PORT: {{ .Values.config.smtp.port | quote }}
  HASIR_SMTP_FROM: {{ .Values.config.smtp.from | quote }}
  HASIR_SMTP_USETLS: {{ .Values.config.smtp.useTls | quote }}
  HASIR_SSH_ENABLED: "true"
  HASIR_SSH_PORT: "2222"
  HASIR_SSH_HOSTKEYPATH: "/data/ssh/ssh_host_key"
  HASIR_DASHBOARDURL: "https://{{ .Values.global.domain }}"
  HASIR_SDKGENERATION_OUTPUTPATH: "/data/sdk"
  NEXT_PUBLIC_API_URL: "https://{{ .Values.global.domain }}/api"
