apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "hasir.fullname" . }}-secrets'
  labels:
    {{- include "hasir.labels" . | nindent 4 }}
type: Opaque
data:
  HASIR_POSTGRESQL_PASSWORD: '{{ .Values.postgresql.auth.password | b64enc }}'
  HASIR_JWTSECRET: '{{ .Values.secrets.jwtSecret | b64enc }}'
  HASIR_SMTP_USERNAME: '{{ .Values.secrets.smtp.username | b64enc }}'
  HASIR_SMTP_PASSWORD: '{{ .Values.secrets.smtp.password | b64enc }}'
